SELECT YEAR(SALES_DATE) AS YEAR
      ,MONTH(SALES_DATE) AS MONTH
      ,I.GENDER
      ,COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
LEFT JOIN USER_INFO I ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY 1, 2 ,3
ORDER BY 1, 2, 3