SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY FROM ITEM_INFO A,
(SELECT D.ITEM_ID FROM ITEM_INFO B, ITEM_TREE C, ITEM_TREE D
WHERE B.ITEM_ID = C.ITEM_ID 
AND C.ITEM_ID = D.PARENT_ITEM_ID
AND B.RARITY ='RARE'
) E
WHERE A.ITEM_ID = E.ITEM_ID
ORDER BY A.ITEM_ID DESC